name: skip checks

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  skip-checks:
    runs-on: macos-15
    timeout-minutes: 200
    strategy:
      fail-fast: false
      matrix:
        android-sdk: [6.1, 6.2]
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.4.app/Contents/Developer
    steps:
      # larger projects sometimes yield: Unhandled exception. System.IO.IOException: No space left on device : '/Users/runner/runners/…
      - name: Free Disk Space
        run: sudo rm -rf /Applications/Xcode_14*.app /Applications/Xcode_15*.app /Applications/Xcode_16.app /Applications/Xcode_16.1.app /Applications/Xcode_16_2.app /Applications/Xcode_16.3.app
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
          add-job-summary: never
      - name: Cache Homebrew packages
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/Homebrew
          key: homebrew-packages

      - name: Install Skip
        run: brew install skiptools/skip/skip || (brew update && brew install skiptools/skip/skip)

      - name: Skip Checkup
        run: skip checkup
      #- run: skip checkup --verbose --double-check

      - run: skip init --transpiled-model demo-module DemoModule
      - run: skip init --transpiled-app --appid=xyz.skip.Demo demo-app DemoApp DemoModule
      - run: skip init --transpiled-app --appfair demo-appfair DemoFairApp

      # native model and app init
      - run: skip android sdk install --version ${{ matrix.android-sdk }} --verbose

      - run: skip checkup --verbose --native

      - run: skip checkup --verbose --native-model
      - run: skip init --native-model demo-module-native DemoModule
      - run: skip init --native-model --kotlincompat demo-module-kotlincompat DemoModule
      - run: skip init --native-model --appid=xyz.skip.Demo demo-native-model-app DemoApp DemoModule

      - run: skip checkup --verbose --native-app
      - run: skip init --native-app --appid=xyz.skip.Demo demo-app-native DemoApp
      - run: skip init --native-app --native-model --appid=xyz.skip.Demo demo-app-native-model DemoApp DemoModel
      - run: skip export --project demo-app-native-model --arch x86_64 --arch aarch64 --arch armv7

